.MODEL SMALL
.STACK 100H
.CODE

MAIN PROC  
    MOV AL,0BH     ;DIVIDENT SUMT BE IN AL
    MOV BL,5H      ;DIVISOR
    DIV BL         ;ONLY PAREMETER IS DIVISOR
                   ;ANS GOES TO AL RIMINDER GOES TO AH
   
   EXIT:
   
   MOV AH,4CH
   INT 21H
   MAIN ENDP
END MAIN